language: java

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk7

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Install Puppet to test the Puppet plugin.
# Do not use "sudo gem install", it alters the system path.
before_script:
  - sudo apt-get update -y
  - sudo apt-get install rubygems
  - gem install puppet

# For debug only
#  - puppet --version

# Build with Maven.
script:
  - ./travis-build.sh

# Actions to perform after the build.
after_success:
  - ./travis-after-success.sh
