language: java

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Build with Maven.
# Use -q option to only display Maven errors and warnings.
script:
  - mvn clean install -q

# Notify Coveralls.
# Use -q option to only display Maven errors and warnings.
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura -q
