language: java

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk7

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Install Puppet to test the Puppet plugin.
# Do not use "sudo gem install", it alters the system path.
before_script:
  - sudo apt-get install rubygems
  - gem install puppet

# For debug only
#  - puppet --version

# Build with Maven.
# Use -q option to only display Maven errors and warnings.
script:
  - mvn clean install -q

# Actions to perform after the build (only for Java 6).
after_success:
  - ./after_success.sh
