language: java
sudo: false

# Skip the default Maven command launched by Travis.
# By default, it is "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install: true

# ENV variables
env:
  - ROBOCONF_IT_TIMEOUT=60000

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Install Puppet to test the Puppet plugin.
addons:
  apt:
    packages:
    - wget

# Gem, NPM and Gulp seem to be available by default now.
#before_script:
#  - gem install puppet
#  - npm install -g gulp

# For debug only
#  - puppet --version

# Build with Maven.
script:
  - ./travis-build.sh

# Actions to perform after the build.
after_success:
  - ./travis-after-success.sh
