language: java

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Install Puppet to test the Puppet plugin
before_script:
  - sudo apt-get install rubygems
  - sudo gem install puppet
  - sudo gem install puppet-module
  - puppet --version
  - export PATH=/usr/local/bin:$PATH

# Build with Maven.
# Use -q option to only display Maven errors and warnings.
script:
  - mvn clean install -q

# Notify Coveralls.
# Use -q option to only display Maven errors and warnings.
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura -q
