language: java

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

# Make sure there is a RabbitMq server
services:
  - rabbitmq
  
# Roboconf uses a snapshot version of Woorea for OpenStack.
# Since there is no snapshot repository, we will build it locally.
before_install:
  - git clone git://github.com/woorea/openstack-java-sdk.git ~/builds/repo2
  - pushd ~/builds/repo2
  - mvn clean install -Dskip.sign=true
  - popd
  
# This is really dirty!!!

# Build with Maven.
# Use -q option to only display Maven errors and warnings.
script:
  - mvn clean install -q

# Notify Coveralls.
# Use -q option to only display Maven errors and warnings.
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura -q
