language: java

# Test several JDK
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Install Puppet to test the Puppet plugin
# Travis uses Ubuntu 12.04 LTS, which has some problems with Puppet. => Install Rack
# See https://groups.google.com/forum/#!msg/puppet-users/Z71Bj0uddfs/r5OmWqGs_zYJ
before_script:
  - sudo apt-get install rubygems
  - sudo gem install puppet
  - sudo gem install puppet-module
  - sudo gem install rack --version=1.1.0
  - sudo gem install rack --version=1.1.2
  - puppet --version

# Build with Maven.
# Use -q option to only display Maven errors and warnings.
script:
  - mvn clean install -q

# Notify Coveralls.
# Use -q option to only display Maven errors and warnings.
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura -q
